### ISSUE TITLE
PolicyManager

### ISSUE THREAD

**Issue by zoozooll** [chloette/how-to-demo#1]
在获取layout文件时候出现异常崩溃。 而从日志上看发现在覆盖wrapcontextde getSystemService 时PolicyManager类找不到。
java.lang.ClassNotFoundException: com.android.internal.policy.PolicyManager
是否后续的版本已经不用这个类了。
全部日志如下：
### 01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err: java.lang.ClassNotFoundException: com.android.internal.policy.PolicyManager
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at java.lang.Class.classForName(Native Method)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at java.lang.Class.forName(Class.java:453)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at java.lang.Class.forName(Class.java:378)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at com.example.testapk.TargetContext.getSystemService(TargetContext.java:78)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at com.tabolt.reflect.ReflectResource.getResApkLayoutView(ReflectResource.java:48)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at com.example.testapk.MainActivity.showDialog(MainActivity.java:147)
01-09 14:39:20.533 14832-14832/com.example.testapk W/System.err:     at com.example.testapk.MainActivity.onClick(MainActivity.java:136)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.view.View.performClick(View.java:6329)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.view.View$PerformClick.run(View.java:25004)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.os.Handler.handleCallback(Handler.java:809)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.os.Looper.loop(Looper.java:218)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7338)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
01-09 14:39:20.534 14832-14832/com.example.testapk W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.policy.PolicyManager" on path: DexPathList[[zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/base.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
01-09 14:39:20.535 14832-14832/com.example.testapk W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
01-09 14:39:20.535 14832-14832/com.example.testapk W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
01-09 14:39:20.535 14832-14832/com.example.testapk W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-09 14:39:20.535 14832-14832/com.example.testapk W/System.err: 	... 16 more
01-09 14:39:20.538 14832-14832/com.example.testapk D/AndroidRuntime: Shutting down VM
01-09 14:39:20.541 14832-14832/com.example.testapk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.example.testapk, PID: 14832
                                                                     android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.example.resapk.views.ImageViewEx
                                                                     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.example.resapk.views.ImageViewEx
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.resapk.views.ImageViewEx" on path: DexPathList[[zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/base.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.testapk-m4RBw7DHGr1WEL-yS2Zhww==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
                                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
                                                                         at com.tabolt.reflect.ReflectResource.getResApkLayoutView(ReflectResource.java:49)
                                                                         at com.example.testapk.MainActivity.showDialog(MainActivity.java:147)
                                                                         at com.example.testapk.MainActivity.onClick(MainActivity.java:136)
                                                                         at android.view.View.performClick(View.java:6329)
                                                                         at android.view.View$PerformClick.run(View.java:25004)
                                                                         at android.os.Handler.handleCallback(Handler.java:809)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:218)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7338)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by zoozooll** [comment]
Fixed 
The newer version of android has quit `com.android.internal.policy.PolicyManage`r.  Instead for `com.android.internal.policy.PolicyManager`. 
We can use the follow code in method `getSystemService`

```
Class policyClass = Class.forName("com.android.internal.policy.PhoneLayoutInflater");
					Constructor<?> localConstructor = policyClass.getConstructor(new Class[]{Context.class});
					mLayoutInflater = (LayoutInflater) localConstructor.newInstance(new Object[]{this});
```
